CREATE TABLE IF NOT EXISTS `glomap_db`.`USER` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_TYPE` CHAR(1) NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  `PWD` VARCHAR(32) NULL,
  `ROLE_ADMIN` TINYINT(1) NOT NULL,
  `STATUS` TINYINT(1) NOT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `glomap_db`.`GALLERY` (
  `GALLERY_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(11) NOT NULL,
  `LEGEND` VARCHAR(250) NOT NULL,
  `DESCRIPTION` VARCHAR(400) NULL,
  `CREATION_DT` DATETIME NOT NULL,
  `LAST_UPDATE_DT` DATETIME NULL,
  `STATUS` TINYINT(1) NOT NULL,
  PRIMARY KEY (`GALLERY_ID`),
  INDEX `fk_GALLERY_USER_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_GALLERY_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `glomap_db`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `glomap_db`.`IMAGE` (
  `IMAGE_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `GALLERY_ID` INT(11) NOT NULL,
  `IMAGE` LONGBLOB NOT NULL,
  `IMAGE_HEIGHT` INT(5) NULL,
  `IMAGE_WIDTH` INT(5) NULL,
  `IMAGE_SIZE` VARCHAR(50) NULL,
  `IMAGE_THUMB` MEDIUMBLOB NOT NULL,
  `IMAGE_THUMB_HEIGHT` INT(5) NULL,
  `IMAGE_THUMB_WIDTH` INT(5) NULL,
  `IMAGE_THUMB_SIZE` VARCHAR(50) NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `LEGEND` VARCHAR(250) NULL,
  `COVER_IMAGE` TINYINT(1) NOT NULL,
  `CREATION_DT` DATETIME NOT NULL,
  PRIMARY KEY (`IMAGE_ID`),
  INDEX `fk_IMAGE_GALLERY1_idx` (`GALLERY_ID` ASC),
  CONSTRAINT `fk_IMAGE_GALLERY1`
    FOREIGN KEY (`GALLERY_ID`)
    REFERENCES `glomap_db`.`GALLERY` (`GALLERY_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `glomap_db`.`CONTENT` (
  `CONTENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(11) NOT NULL,
  `CONTENT_TYPE` INT NOT NULL,
  `COMPONENT_ID` VARCHAR(100) NOT NULL,
  `URL` VARCHAR(300) NOT NULL,
  `TITLE` VARCHAR(250) NOT NULL,
  `CONTENT` LONGTEXT NOT NULL,
  `MANAGEMENT` VARCHAR(9) NULL,
  `PERIOD_START_MONTH` VARCHAR(2) NULL,
  `PERIOD_START_YEAR` VARCHAR(4) NULL,
  `PERIOD_END_MONTH` VARCHAR(2) NULL,
  `PERIOD_END_YEAR` VARCHAR(4) NULL,
  `CREATION_DT` DATETIME NOT NULL,
  `LAST_UPDATE_DT` DATETIME NULL,
  `STATUS` TINYINT(1) NOT NULL,
  PRIMARY KEY (`CONTENT_ID`, `USER_ID`),
  INDEX `fk_CONTENT_USER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_CONTENT_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `glomap_db`.`USER` (`USER_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB

ALTER TABLE glomap1.CONTENT ADD `MANAGEMENT` VARCHAR(9) NULL AFTER `CONTENT`;

ALTER TABLE glomap1.CONTENT ADD `PERIOD_START_MONTH` VARCHAR(2) NULL AFTER `MANAGEMENT`;

ALTER TABLE glomap1.CONTENT ADD `PERIOD_START_YEAR` VARCHAR(4) NULL AFTER `PERIOD_START_MONTH`;

ALTER TABLE glomap1.CONTENT ADD `PERIOD_END_MONTH` VARCHAR(2) NULL AFTER `PERIOD_START_YEAR`;

ALTER TABLE glomap1.CONTENT ADD `PERIOD_END_YEAR` VARCHAR(4) NULL AFTER `PERIOD_END_MONTH`;

CREATE TABLE IF NOT EXISTS `mydb`.`CONTENT` (
  `CONTENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(11) NOT NULL,
  `CONTENT_TYPE` INT NOT NULL,
  `COMPONENT_ID` VARCHAR(100) NOT NULL,
  `URL` VARCHAR(300) NOT NULL,
  `TITLE` VARCHAR(250) NOT NULL,
  `CONTENT` LONGTEXT NOT NULL,
  `MANAGEMENT` VARCHAR(9) NULL,
  `CREATION_DT` DATETIME NOT NULL,
  `LAST_UPDATE_DT` DATETIME NULL,
  `STATUS` TINYINT(1) NOT NULL,
  `PERIOD_START_MONTH` VARCHAR(2) NULL,
  `PERIOD_START_YEAR` VARCHAR(4) NULL,
  `PERIOD_END_MONTH` VARCHAR(2) NULL,
  `PERIOD_END_YEAR` VARCHAR(4) NULL,
  PRIMARY KEY (`CONTENT_ID`, `USER_ID`),
  INDEX `fk_CONTENT_USER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_CONTENT_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mydb`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


CREATE TABLE IF NOT EXISTS `glomap_db`.`PARAMETER` (
  `PARAMETER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `KEY` VARCHAR(100) NOT NULL,
  `VALUE` LONGTEXT NOT NULL,
  PRIMARY KEY (`PARAMETER_ID`))
ENGINE = InnoDB

ALTER TABLE CONTENT ADD STATE CHAR(1);

UPDATE CONTENT SET STATE = 'A';